insert into public.wm_investment_products (
  id,
  name,
  category,
  return_min,
  return_max,
  return_display,
  min_investment_ugx,
  risk_level,
  horizon_min_years,
  horizon_max_years,
  description,
  projection_note,
  stale_after_days,
  source_url,
  expert_note,
  is_featured,
  is_active
)
values
  (
    'ug-treasury-bond',
    'Uganda Treasury Bond',
    'bond',
    0.14,
    0.16,
    '14-16%',
    100000,
    'low',
    2,
    15,
    'Government-backed instrument suitable for long-horizon savers seeking stable returns.',
    'Rates vary by tenor and auction cycle.',
    30,
    'https://www.bou.or.ug',
    'Core anchor allocation for conservative wealth plans.',
    true,
    true
  ),
  (
    'ug-balanced-unit-trust',
    'Balanced Unit Trust (UGX)',
    'unit_trust',
    0.1,
    0.14,
    '10-14%',
    50000,
    'medium',
    3,
    15,
    'Professionally managed pooled fund mixing fixed income and equities.',
    'Net returns depend on manager fees and market cycles.',
    30,
    'https://www.cma.ug',
    'Useful growth sleeve alongside bonds for balanced portfolios.',
    true,
    true
  ),
  (
    'ug-insurance-savings-plan',
    'Insurance Savings Plan',
    'insurance',
    0.08,
    0.12,
    '8-12%',
    100000,
    'low_medium',
    5,
    20,
    'Long-term disciplined savings with bundled protection features.',
    'Liquidity constraints can apply before maturity.',
    45,
    'https://ira.go.ug',
    'Best for users prioritizing consistency over high upside.',
    false,
    true
  ),
  (
    'ug-use-bluechip-equity',
    'USE Blue-Chip Equity Basket',
    'equity',
    0.12,
    0.2,
    '12-20%',
    100000,
    'high',
    5,
    20,
    'Diversified exposure to established listed companies on the Uganda Securities Exchange.',
    'Expected volatility is higher than bonds and unit trusts.',
    30,
    'https://www.use.or.ug',
    'High-upside sleeve for long-horizon investors comfortable with drawdowns.',
    false,
    true
  )
on conflict (id) do update
set
  name = excluded.name,
  category = excluded.category,
  return_min = excluded.return_min,
  return_max = excluded.return_max,
  return_display = excluded.return_display,
  min_investment_ugx = excluded.min_investment_ugx,
  risk_level = excluded.risk_level,
  horizon_min_years = excluded.horizon_min_years,
  horizon_max_years = excluded.horizon_max_years,
  description = excluded.description,
  projection_note = excluded.projection_note,
  stale_after_days = excluded.stale_after_days,
  source_url = excluded.source_url,
  expert_note = excluded.expert_note,
  is_featured = excluded.is_featured,
  is_active = excluded.is_active,
  last_updated = now();
